baseURL = "https://example.com"
title   = "AI Blog"
languageCode = "en-us"
theme = "hello-friend-ng"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 1
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 2
  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "/research/"
    weight     = 3
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = 4